export const APP_PERMISSIONS = {
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_RIGHTS: 'users:rights',
  STUDENTS_READ: 'students:read',
  STUDENTS_WRITE: 'students:write',
  TEACHERS_READ: 'teachers:read',
  TEACHERS_WRITE: 'teachers:write',
  CLASSES_READ: 'classes:read',
  CLASSES_WRITE: 'classes:write',
  GRADES_READ: 'grades:read',
  GRADES_WRITE: 'grades:write',
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_WRITE: 'payments:write',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_WRITE: 'attendance:write',
  REPORTS_READ: 'reports:read',
  REPORTS_WRITE: 'reports:write',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
} as const;

export type AppPermission = (typeof APP_PERMISSIONS)[keyof typeof APP_PERMISSIONS];

export const WILDCARD_PERMISSION = '*';

export const ROLE_PERMISSION_DEFAULTS: Record<string, readonly string[]> = {
  ADMIN: [WILDCARD_PERMISSION],
  AGENT: [
    APP_PERMISSIONS.STUDENTS_READ,
    APP_PERMISSIONS.STUDENTS_WRITE,
    APP_PERMISSIONS.CLASSES_READ,
    APP_PERMISSIONS.ATTENDANCE_READ,
    APP_PERMISSIONS.ATTENDANCE_WRITE,
    APP_PERMISSIONS.GRADES_READ,
    APP_PERMISSIONS.PAYMENTS_READ,
    APP_PERMISSIONS.PAYMENTS_WRITE,
    APP_PERMISSIONS.REPORTS_READ,
  ],
  ENSEIGNANT: [
    APP_PERMISSIONS.STUDENTS_READ,
    APP_PERMISSIONS.CLASSES_READ,
    APP_PERMISSIONS.ATTENDANCE_READ,
    APP_PERMISSIONS.ATTENDANCE_WRITE,
    APP_PERMISSIONS.GRADES_READ,
    APP_PERMISSIONS.GRADES_WRITE,
    APP_PERMISSIONS.REPORTS_READ,
  ],
  TEACHER: [
    APP_PERMISSIONS.STUDENTS_READ,
    APP_PERMISSIONS.CLASSES_READ,
    APP_PERMISSIONS.ATTENDANCE_READ,
    APP_PERMISSIONS.ATTENDANCE_WRITE,
    APP_PERMISSIONS.GRADES_READ,
    APP_PERMISSIONS.GRADES_WRITE,
    APP_PERMISSIONS.REPORTS_READ,
  ],
  PARENT: [
    APP_PERMISSIONS.STUDENTS_READ,
    APP_PERMISSIONS.ATTENDANCE_READ,
    APP_PERMISSIONS.GRADES_READ,
    APP_PERMISSIONS.PAYMENTS_READ,
  ],
  ELEVE: [
    APP_PERMISSIONS.ATTENDANCE_READ,
    APP_PERMISSIONS.GRADES_READ,
  ],
  STUDENT: [
    APP_PERMISSIONS.ATTENDANCE_READ,
    APP_PERMISSIONS.GRADES_READ,
  ],
};
