export enum TypePaiement {
  FRAIS_PREINSCRIPTION = "FRAIS_PREINSCRIPTION",
  FRAIS_INSCRIPTION = "FRAIS_INSCRIPTION",
  FRAIS_SCOLAIRE = "FRAIS_SCOLAIRE",
  FRAIS_TRANSPORT = "FRAIS_TRANSPORT",
  FRAIS_CANTINE = "FRAIS_CANTINE",
  FRAIS_EXAMEN = "FRAIS_EXAMEN",
  FRAIS_MATIERES = "FRAIS_MATIERES",
  FRAIS_MATERIEL = "FRAIS_MATERIEL",
  FRAIS_UNIFORME = "FRAIS_UNIFORME",
  FRAIS_ASSURANCE = "FRAIS_ASSURANCE",
  FRAIS_BIBLIOTHEQUE = "FRAIS_BIBLIOTHEQUE",
  FRAIS_ACTIVITE = "FRAIS_ACTIVITE",
  FRAIS_PHOTO = "FRAIS_PHOTO",
  FRAIS_AUTRES = "FRAIS_AUTRES",

  // Catégorie : Services de soutien
  SOUTIEN_PSYCHOLOGIQUE = "SOUTIEN_PSYCHOLOGIQUE",
  SOUTIEN_MEDICAL = "SOUTIEN_MEDICAL",
  SOUTIEN_SOCIAL = "SOUTIEN_SOCIAL",
  SOUTIEN_JURIDIQUE = "SOUTIEN_JURIDIQUE",
  SOUTIEN_TECHNIQUE = "SOUTIEN_TECHNIQUE",
  SOUTIEN_ADMINISTRATIF = "SOUTIEN_ADMINISTRATIF",
}
